### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by john-kliem** [PatP15/aquaticus-docker#3]
This could just be an error on my end, I am trying to build the docker image from windows and I'm getting an error calling the ./build.sh script in moos-ivp-rlagent.

**Comment by PatP15** [comment]
Hmmm I haven't been able to replicate that error on my Linux. I also don't have a Windows so I can't test it. Did changing the permissions not help at all? I may have changed them locally and that's why it works on my computer.

**Comment by john-kliem** [comment]
I tried changing the permissions, but it still seems to error out in the same place.

**Comment by PatP15** [comment]
Do you have access to a linux computer by any chance? Would you be able to test it on there? If not, I'll bug someone to test it on their Windows.

**Comment by john-kliem** [comment]
Seems like trying to build from linux, results in an error in a different spot:

E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
